### ISSUE TITLE
Esqueceu de arrumar aqui

### ISSUE THREAD

**Issue by marcopandolfo** [DanielHe4rt/markdown-portfolio#1]
![image](https://user-images.githubusercontent.com/40467826/49762420-dacb4b80-fcb0-11e8-89dc-0888b805bb25.png)

**Comment by danielhe4rt** [comment]
Obrigado pelo aviso! Fixado no commit https://github.com/DanielHe4rt/markdown-portfolio/commit/ed5d931edafcfd17af5a94603828d19132c29e89
